#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def lcm(arr):
    result = arr[0]
    for i in range(1, len(arr)):
        result = lcm2(result, arr[i])
    return result

def lcm2(a, b):
    return (a*b)/gcd2(a, b)

def gcd(arr):
    result = arr[0]
    for i in range(1, len(arr)):
        result = gcd2(result, arr[i])
        
    return result

def gcd2(a, b):
    while b > 0:
        temp = b
        b = a%b
        a = temp
    return a

def getTotalX(a, b):
    # Write your code here
    lcm_total = int(lcm(a))
    gcd_total = int(gcd(b))
    lcm_copy = lcm_total
    count = 0
    while lcm_total <= gcd_total:
        print(lcm_total)
        if gcd_total % lcm_total == 0:
            count += 1
        lcm_total = lcm_total + lcm_copy
        
    return count
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
