#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    temp_score = [scores[0]]
    min_count = 0
    max_count = 0
    for i in range(1, len(scores)):
        new_elem = scores[i]
        if new_elem in temp_score:
            temp_score.append(new_elem)
        else:
            temp_score.append(new_elem)
            if max(temp_score) == new_elem:
                max_count += 1
            elif min(temp_score) == new_elem:
                min_count += 1
            else:
                pass
        
    return max_count, min_count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
